- name: Install MongoDB
  hosts: localhost
  become: yes

  tasks:
          - name: Add MongoDB GPG key
            apt_key:
                    url: https://www.mongodb.org/static/pgp/server-5.0.asc
                    state: present

          - name: Add MongoDB repo
            apt_repository:
                    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse
                    state: present

          - name: update apt
            apt:
                    update_cache: yes

          - name: install mongodb
            apt:
                    name: mongodb-org
                    state: present

          - name: start mongodb service
            service:
                    name: mongod
                    state: started
                    enabled: yes
            notify:
                    - restart mongod

  handlers:
          - name: restart mongod
            service:
                    name: mongod
                    state: restarted
