- name: mongodb remote configs
  hosts: ubuntu2
  become: yes

  tasks:
          - name: allow remote connections
            replace:
                    path: /etc/mongod.conf
                    regexp: '^(net:.*bindIp:).*'
                    replace: '\1 127.0.0.1, 0.0.0.0'

          - name: create mongodb user for remote mongodump
            command: "sudo -u mongodb /usr/bin/mongo admin --eval 'db.createUser({user: \"remoteUser\", pwd: \"remotePassword\", roles: [\"root\", \"readWriteAnyDatabase\"]})'"
            notify:
                    - restart mongod
  handlers:
          - name: restart mongod
            service:
                    name: mongod
                    state: restarted
