- name: mongodb backup
  hosts: 10.1.0.5
  become: true
  tasks:
          - name: import MongoDB GPG key
            apt_key:
                    url: https://www.mongodb.org/static/pgp/server-4.4.asc
                    state: present

          - name: add mongodb repo
            apt_repository:
                    repo: "deb http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/4.4 multiverse"
                    state: present

          - name: update apt cache
            apt:
                    update_cache: yes

          - name: install mongodb tools
            apt:
                    name: mongodb-org-tools
                    state: present

          - name: create backup directory
            file:
                    path: ~/mongodb_backup
                    state: directory

          - name: perform mongodb backup
            command: mongodump --host 10.1.0.4 --port 27017 -u remoteUser -p remotePassword --authenticationDatabase admin --out ~/mongodb_backup

          - name: archive backup
            command: tar -czvf ~/mongodb_backup/archive.tar.gz -C ~/mongodb_backup .
